name: "Terraform Plan"

trigger:
  branches:
    include:
      - main

pool:
  name: Default

steps:

- task: TerraformInstaller@0
  displayName: "Install Terraform"
  inputs:
    terraformVersion: '1.1.0'

- task: TerraformTaskV4@4
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'Pay-As-You-Go(1)(f510d486-a17f-44f2-a1c4-63a7186e923c)'
    backendAzureRmResourceGroupName: 'shivraj'
    backendAzureRmStorageAccountName: 'tfstorageaccountshivraj'
    backendAzureRmContainerName: 'terrraformcontainer'
    backendAzureRmKey: 'tf/terraform.tfstate'
  
# - task: PublishBuildArtifacts@1
#   inputs:
#     pathtoPublish: '$(Build.SourcesDirectory)/terraform.tfplan'
#     artifactName: 'terraformPlan'
#     publishLocation: 'Container'