name: "Terraform Plan"

parameters:
- name: Enviroment
  displayName: Environment
  type: string
  default: "Dev"
  values:
  - "Dev"
  - "test"
  - "prod"

trigger:
  branches:
    include:
      - main

pool:
  name: Default

steps:

- task: TerraformInstaller@0
  displayName: "Install Terraform"
  inputs:
    terraformVersion: '1.1.0'

- task: TerraformTaskV4@4
  displayName: "Terraform init"
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'Pay-As-You-Go(1)(f510d486-a17f-44f2-a1c4-63a7186e923c)'
    backendAzureRmResourceGroupName: 'tfbackupazure'
    backendAzureRmStorageAccountName: 'tfstorageaccountshivraj'
    backendAzureRmContainerName: 'terrraformcontainer'
    backendAzureRmKey: 'terraform.tfstate'
    
- task: TerraformTaskV4@4
  displayName: "Terraform plan"
  inputs:
    provider: 'azurerm'
    command: 'plan'
    commandOptions: '-out=terraform.tfplan'
    environmentServiceNameAzureRM: 'Pay-As-You-Go(1)(f510d486-a17f-44f2-a1c4-63a7186e923c)'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.SourcesDirectory)/terraform.tfplan'
    artifactName: 'terraformPlan'
    publishLocation: 'Container'    
- task: TerraformTaskV4@4
  displayName: "Terraform apply "
  inputs:
    provider: 'azurerm'
    command: 'apply'
    environmentServiceNameAzureRM: 'Pay-As-You-Go(f510d486-a17f-44f2-a1c4-63a7186e923c)'

- task: TerraformTaskV4@4
  condition: always()
  displayName: "Terraform Destroy"
  inputs:
    provider: 'azurerm'
    command: 'destroy'
    environmentServiceNameAzureRM: 'Pay-As-You-Go(f510d486-a17f-44f2-a1c4-63a7186e923c)'
